### ISSUE TITLE
Re-trained VAE vs. pre-trained VAE

### ISSUE THREAD

**Issue by huge123** [lxa9867/ControlVAR#11]
Thanks for sharing this great work. 

but I have a question, Have you compared the pre-trained VAE of VAR with the VAE trained by yourself, as I see a train vqvae script in this repo, I wonder why you are using the pretrained one instead of using the one trained by yourself?

**Comment by lxa9867** [comment]
Hi, 

Thanks for your interest. 

If you mean the Imagefolder tokenizer, it will definitely result in better performance. We used the VAR's tokenizer because we also adapted their pretrained VAR weights (d16-d30) as initialization. This will make the training much faster (as I don't have enough computational resources for d20+ experiments).

**Comment by huge123** [comment]
Thank you for the reply. It is not about the Imagefolder tokenizer. I wonder have you used the following script to re-train a VAR tokenizer?
https://github.com/lxa9867/ControlVAR/blob/main/train_vqvae.py

**Comment by lxa9867** [comment]
Yes, we trained VAR tokenizer with this script. However, the result is not satisfactory. Training tokenizers for next-scale AR requires a lot of design. You may refer to the [Imagefolder](https://github.com/lxa9867/ImageFolder) repo later if you want to train a new tokenizer on your dataset.

**Comment by huge123** [comment]
I see, thank  you very much
